# Prépare le conteneur Nginx
FROM nginx:latest as nginx

# Copie la configuration de Nginx
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Copie le contenu du build Node.js dans le dossier de Nginx
COPY --from=node /usr/src/app /usr/share/nginx/html

# Expose le port 80 pour Nginx
EXPOSE 80

# Commande de démarrage du conteneur
CMD ["nginx", "-g", "daemon off;"]