version: '3.8'

services:
  server1:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    container_name: server1
    expose:
      - "8000"
    volumes:
      - .:/server
    working_dir: /server
    command: node server/js/main.js

  server2:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    container_name: server2
    expose:
      - "8000"
    volumes:
      - .:/server
    working_dir: /server
    command: node server/js/main.js

  server3:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    container_name: server3
    expose:
      - "8000"
    volumes:
      - .:/server
    working_dir: /server
    command: node server/js/main.js

  server4:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    container_name: server4
    expose:
      - "8000"
    volumes:
      - .:/server
    working_dir: /server
    command: node server/js/main.js

  server5:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    container_name: server5
    expose:
      - "8000"
    volumes:
      - .:/server
    working_dir: /server
    command: node server/js/main.js

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - server3
      - server4
      - server5